[project]
name = "cookiecutter-airpackage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cookiecutter>=2.6.0",
    "rust-just>=1.43.0",
]
